### ISSUE TITLE
Unable to configure using Active Directory

### ISSUE THREAD

**Issue by 80O** [hansohn/jupyterhub-ldap-authenticator#16]
I'm trying to get active directory to work. This is my current configuration:

```
c.JupyterHub.authenticator_class = 'ldapauthenticator.LDAPAuthenticator'
c.LDAPAuthenticator.server_hosts = ['ldap://dc12r2n1.company.local']
c.LDAPAuthenticator.user_search_base = 'OU=Development,OU=company Users,DC=company,DC=local'
c.LDAPAuthenticator.user_search_filter = '(&(objectCategory=person)(objectClass=user)(sAMAccountName={username}))'
c.LDAPAuthenticator.user_membership_attribute = 'memberOf'
c.LDAPAuthenticator.allowed_groups = ['DC=company,DC=local']
c.LDAPAuthenticator.username_pattern = '[a-zA-Z0-9_.][a-zA-Z0-9_.-]{8,20}[a-zA-Z0-9_.$-]?'
c.LDAPAuthenticator.create_user_home_dir_cmd = ['mkhomedir_helper']
```

When I start jupyter server I get the following error:

```
[I 2019-09-10 14:17:37.939 JupyterHub proxy:460] Generating new CONFIGPROXY_AUTH_TOKEN
[E 2019-09-10 14:17:37.940 JupyterHub app:2482]
    Traceback (most recent call last):
      File "/home/hub/anaconda3/lib/python3.7/site-packages/jupyterhub/app.py", line 2479, in launch_instance_async
        await self.initialize(argv)
      File "/home/hub/anaconda3/lib/python3.7/site-packages/jupyterhub/app.py", line 2133, in initialize
        await self.init_users()
      File "/home/hub/anaconda3/lib/python3.7/site-packages/jupyterhub/app.py", line 1529, in init_users
        raise ValueError("username %r is not valid" % username)
    ValueError: username 'hub' is not valid

[D 2019-09-10 14:17:37.941 JupyterHub application:647] Exiting application: jupyterhub
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<JupyterHub.launch_instance_async() done, defined at /home/hub/anaconda3/lib/python3.7/site-packages/jupyterhub/app.py:2477> exception=SystemExit(1)>
Traceback (most recent call last):
  File "/home/hub/anaconda3/lib/python3.7/site-packages/jupyterhub/app.py", line 2479, in launch_instance_async
    await self.initialize(argv)
  File "/home/hub/anaconda3/lib/python3.7/site-packages/jupyterhub/app.py", line 2133, in initialize
    await self.init_users()
  File "/home/hub/anaconda3/lib/python3.7/site-packages/jupyterhub/app.py", line 1529, in init_users
    raise ValueError("username %r is not valid" % username)
ValueError: username 'hub' is not valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hub/anaconda3/lib/python3.7/site-packages/jupyterhub/app.py", line 2492, in launch_instance
    loop.start()
  File "/home/hub/anaconda3/lib/python3.7/site-packages/tornado/platform/asyncio.py", line 148, in start
    self.asyncio_loop.run_forever()
  File "/home/hub/anaconda3/lib/python3.7/asyncio/base_events.py", line 539, in run_forever
    self._run_once()
  File "/home/hub/anaconda3/lib/python3.7/asyncio/base_events.py", line 1775, in _run_once
    handle._run()
  File "/home/hub/anaconda3/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/home/hub/anaconda3/lib/python3.7/site-packages/jupyterhub/app.py", line 2483, in launch_instance_async
    self.exit(1)
  File "/home/hub/anaconda3/lib/python3.7/site-packages/traitlets/config/application.py", line 648, in exit
    sys.exit(exit_status)
SystemExit: 1
(base) hub@jupyterserver:~$

```

**Comment by hansohn** [comment]
Hello @80O 

Unfortunately, I don't currently have an Active Directory instance at my disposal to test with but I do see a few errors in your config that may yield you different results.

First, you have your domain listed as your allowed_groups. 

`c.LDAPAuthenticator.allowed_groups = ['DC=company,DC=local']`

I believe you will need to update this to whatever valid AD group you are using to permit jupyterhub access and verify that `hub` is a member of it.

Second, has to do with your username_regex pattern:

`'[a-zA-Z0-9_.][a-zA-Z0-9_.-]{8,20}[a-zA-Z0-9_.$-]?'`

This pattern is looking for a username between 8 and 20 characters and `hub` doesn't fit that criteria. I can't remember where I got that regex match sequence from so I may need to revisit current Microsoft sAMAccountName attribute specs. You could update it to the following though to allow `hub` to be accepted.

`'[a-zA-Z0-9_.][a-zA-Z0-9_.-]{2,20}[a-zA-Z0-9_.$-]?'`

This might not solve all your problems but it should at least get you closer to a successful implementation. Please let me know your results.

Cheers!
