### ISSUE TITLE
Failed to create system user

### ISSUE THREAD

**Issue by jameholme** [hansohn/jupyterhub-ldap-authenticator#17]
```[I 2019-10-04 14:20:32.529 JupyterHub ldapauthenticator:587] User 'jholme' sucessfully authenticated against ldap server [‘IPADDRESS’].
[I 2019-10-04 14:20:32.534 JupyterHub ldapauthenticator:290] Creating 'jholme' user home directory using command 'mkhomedir_helper jholme'
[E 2019-10-04 14:20:32.538 JupyterHub web:1788] Uncaught exception POST /hub/login?next= (::ffff:IPADDRESS)
    HTTPServerRequest(protocol='https', host='company.com', method='POST', uri='/hub/login?next=', version='HTTP/1.1', remote_ip='::ffff:IPADDRESS)
    Traceback (most recent call last):
      File "/usr/local/lib64/python3.6/site-packages/tornado/web.py", line 1699, in _execute
        result = await result
      File "/usr/local/lib/python3.6/site-packages/jupyterhub/handlers/login.py", line 144, in post
        user = await self.login_user(data)
      File "/usr/local/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 697, in login_user
        user = await self.auth_to_user(authenticated)
      File "/usr/local/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 676, in auth_to_user
        await maybe_future(self.authenticator.add_user(user))
      File "/usr/local/lib/python3.6/site-packages/ldapauthenticator/ldapauthenticator.py", line 269, in add_user
        yield gen.maybe_future(self.add_user_home_dir(username))
      File "/usr/local/lib/python3.6/site-packages/ldapauthenticator/ldapauthenticator.py", line 295, in add_user_home_dir
        raise RuntimeError("Failed to create system user %s: %s" % (username, err))
    RuntimeError: Failed to create system user jholme:

[E 2019-10-04 14:20:32.548 JupyterHub log:166] {
      "X-Forwarded-Host": "company.com",
      "X-Forwarded-Proto": "https",
      "X-Forwarded-Port": "443",
      "X-Forwarded-For": "::ffff:IPADDRESS",
      "Accept-Language": "en-US,en;q=0.9",
      "Accept-Encoding": "gzip, deflate, br",
      "Referer": "https://company.com/hub/login",
      "Sec-Fetch-Site": "same-origin",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3",
      "Sec-Fetch-User": "?1",
      "Sec-Fetch-Mode": "navigate",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36",
      "Content-Type": "application/x-www-form-urlencoded",
      "Upgrade-Insecure-Requests": "1",
      "Origin": "https://company.com",
      "Cache-Control": "max-age=0",
      "Content-Length": "51",
      "Connection": "close",
      "Host": "company.com"
    }
[E 2019-10-04 14:20:32.548 JupyterHub log:174] 500 POST /hub/login?next= (@::ffff:IPADDRESS 796.90ms
```
As you can see, it authenticates against the LDAP server, but fails to create user/home directory

**Comment by enlznep** [comment]
Same issue. Any updates on this?

**Comment by jameholme** [comment]
No updates. I am still unable to resolve this. It seems the 'mkhomedir_helper' isn't working. Even when I attempt it manually on the CLI, it does nothing.

**Comment by arunoruto** [comment]
Had the same issue and used the following command to get around the error:
`c.LDAPAuthenticator.create_user_home_dir_cmd = ['adduser', '-m']`

**Comment by jameholme** [comment]
Did you have to update the ldap auth script? Or just the jupyterhub config file? I will try this out on Monday, thanks!

**Comment by arunoruto** [comment]
> Did you have to update the ldap auth script? Or just the jupyterhub config file? I will try this out on Monday, thanks!

I used a new container every time I was trying to figure out to make it work. So I just tried to see what will happen and it worked like a charm.
I don't know if this is a valid fix or a temporary workaround, but it does the same thing as `mkhomedir_helpmer` but also adds the user to the system (which was the problem for me).

**Comment by jameholme** [comment]
Same here, I tried it out, -m didn't work for me, had to use --create-home. 

Otherwise it worked! Thanks!

**Comment by billtzim** [comment]
> Had the same issue and used the following command to get around the error: `c.LDAPAuthenticator.create_user_home_dir_cmd = ['adduser', '-m']`

Faced the same problem, saw this post and found solution with one small correction.
The command to be used is **useradd** and NOT adduser. The useradd has the -m or --create-home paramater

**Comment by hansohn** [comment]
Thanks for the report, @jameholme — and to everyone who shared the workaround (@arunoruto, @billtzim).

This isn't a bug in the plugin so much as an environment mismatch: **`mkhomedir_helper` only creates a home directory for a user that already resolves as a local POSIX account** (e.g. via SSSD/nslcd). In pure-LDAP deployments where the user isn't a local system account, it fails — hence the 500.

The fix is exactly what folks found: point `create_user_home_dir_cmd` at a command that also creates the account. The plugin already supports this fully — no code change needed:

```python
c.LDAPAuthenticator.create_user_home_dir_cmd = ['useradd', '--create-home']
```

(The username is appended as the final argument, and the command runs as the JupyterHub process user, so it needs permission to create accounts — typically root.)

I've documented this in the README (home-directory section) as part of #23 so the next person hits the guidance instead of the 500. Closing once #23 merges.
