### ISSUE TITLE
Jupyterhub create user and home at first login

### ISSUE THREAD

**Issue by JulianTBZ** [hansohn/jupyterhub-ldap-authenticator#7]
Hi, 
I'm running Jupyterhub version 0.9.4 on Ubuntu 16.04 Server.
I have the jupyterhub-ldap-authenticator version 0.3.0 installed. 
With the ldap-autenticator I want to create the user and the home dir on the first login of the user if he exists on my ldap.  
When I try to login with a user I get the following error message: 

`500 : Internal Server Error
`

My current configuration of the LDAP Part in the jupyterhub_config.py file looks like this:

```
c.JupyterHub.authenticator_class = 'ldapauthenticator.LDAPAuthenticator'
c.LDAPAuthenticator.server_hosts =  ['ldap://ldap.example.com:389']
c.LDAPAuthenticator.bind_user_dn = 'uid=binduser,cn=users,dc=ldap,dc=example,dc=com'
c.LDAPAuthenticator.bind_user_password = 'Password'
c.LDAPAuthenticator.user_search_base = 'cn=users,dc=ldap,dc=example,dc=com'
c.LDAPAuthenticator.user_search_filter = '(&(objectClass=posixAccount)(uid={username}))'
c.LDAPAuthenticator.username_pattern = '[a-zA-Z0-9_.][a-zA-Z0-9_.-]{0,252}[a-zA-Z0-9_.$-]?'
c.LDAPAuthenticator.create_user_home_dir = True
c.LDAPAuthenticator.create_user_home_dir_cmd = ['mkhomedir_helper']
But I have now the problem, that i get the following error.
```

This is the output of the Log.

```
[I 2018-11-13 10:40:03.183 JupyterHub log:158] 302 GET /hub/ -> /hub/login (@::ffff:192.168.3.47) 1.19ms
[I 2018-11-13 10:40:03.245 JupyterHub log:158] 200 GET /hub/login (@::ffff:192.168.3.47) 47.94ms
[I 2018-11-13 10:40:11.116 JupyterHub ldapauthenticator:586] User 't1' sucessfully authenticated against ldap server ['ldap://ldap.example.com:389'].
[I 2018-11-13 10:40:11.128 JupyterHub ldapauthenticator:290] Creating 't1' user home directory using command 'mkhomedir_helper t1'
[E 2018-11-13 10:40:11.133 JupyterHub web:1670] Uncaught exception POST /hub/login?next= (::ffff:192.168.3.47)
    HTTPServerRequest(protocol='http', host='192.168.3.49:8000', method='POST', uri='/hub/login?next=', version='HTTP/1.1', remote_ip='::ffff:192.168.3.47')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/login.py", line 81, in post
        user = await self.login_user(data)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/base.py", line 483, in login_user
        await maybe_future(self.authenticator.add_user(user))
      File "/usr/local/lib/python3.6/dist-packages/ldapauthenticator/ldapauthenticator.py", line 269, in add_user
        yield gen.maybe_future(self.add_user_home_dir(username))
      File "/usr/local/lib/python3.6/dist-packages/ldapauthenticator/ldapauthenticator.py", line 295, in add_user_home_dir
        raise RuntimeError("Failed to create system user %s: %s" % (username, err))
    RuntimeError: Failed to create system user t1: 

[E 2018-11-13 10:40:11.146 JupyterHub log:150] {
      "X-Forwarded-Host": "192.168.3.49:8000",
      "X-Forwarded-Proto": "http",
      "X-Forwarded-Port": "8000",
      "X-Forwarded-For": "::ffff:192.168.3.47",
      "Accept-Language": "de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7",
      "Accept-Encoding": "gzip, deflate",
      "Referer": "http://192.168.3.49:8000/hub/login",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36",
      "Content-Type": "application/x-www-form-urlencoded",
      "Upgrade-Insecure-Requests": "1",
      "Origin": "http://192.168.3.49:8000",
      "Cache-Control": "max-age=0",
      "Content-Length": "29",
      "Connection": "close",
      "Host": "192.168.3.49:8000"
    }
[E 2018-11-13 10:40:11.147 JupyterHub log:158] 500 POST /hub/login?next= (@::ffff:192.168.3.47) 603.82ms
```

Thanks

**Comment by ted-strauss-K1** [comment]
What was the solution?

**Comment by orcunuso** [comment]
Having the same problem, any solutions?

**Comment by JulianTBZ** [comment]
My solution is posted on StackOverflow. 
Link: https://stackoverflow.com/questions/52868644/jupyterhub-create-user-and-home-at-login/55627642#55627642
